import textImage from "../img/text.png";
import numberImage from "../img/number.png"
import addressImage from "../img/address.png";
import singleChoiceImage from "../img/single-choice.png"
import multipleChoiceImage from "../img/multiple-choice.png"
import fileImage from "../img/file.png"
import checkboxImage from "../img/checkbox.png"
import phoneImage from "../img/phone.png"
import dateImage from "../img/date.png"
import nameImage from "../img/name.png"
import textareaImage from "../img/text-box.png"
import commentImage from "../img/comment.png"


export const calculation = {
  valid: false,
  elements: [
    { id: 1, type: "OpenBracket", value: "default" },
    { id: 2, type: "Question", value: { dropDown: true, value: "default" } },
    { id: 3, type: "CloseBracket", value: "default" },
    { id: 4, type: "Operator", value: "default" },
    { id: 5, type: "OpenBracket", value: "default" },
    { id: 6, type: "Question", value: { dropDown: true, value: "default" } },
    { id: 7, type: "CloseBracket", value: "default" },
    { id: 8, type: "LastMenu", value: "default" },
  ],
};
export const validation = {
  valid: false,
  elements: [
    { id: 1, type: "OpenBracket", value: "default" },
    {
      id: 2,
      type: "Question",
      isInput: false,
      conditionType: "text",
      value: { dropDown: true, value: "default" },
    },
    { id: 3, type: "Operator", conditionType: "text", value: "default" },
    {
      id: 4,
      type: "Question",
      isInput: true,
      conditionType: "text",
      value: { dropDown: true, value: "default" },
    },
    { id: 5, type: "CloseBracket", value: "default" },
    { id: 6, type: "LastMenu", value: "default" },
  ],
};

export const items = [
  { name: "Text", image: textImage, type: "text" },
  { name: "Number", image: numberImage, type: "number" },
  { name: "Date", image: dateImage, type: "date" },
  { name: "Name", image: nameImage, type: "name" },
  { name: "Phone", image: phoneImage, type: "telephone" },
  { name: "File", image: fileImage, type: "file" },
  { name: "Single Choice", image: singleChoiceImage, type: "single-choice" },
  { name: "Multiple Choice", image: multipleChoiceImage, type: "multiple-choice" },
  { name: "Checkbox", image: checkboxImage, type: "yes/no" },
  { name: "Address", image: addressImage, type: "address" },
  { name: "Text Box", image: textareaImage, type: "textarea" },
  { name: "Comment", image: commentImage, type: "comment" },
];

export const questionsExamples = [
  // {
  //   id: "a",
  //   type: "name",
  //   text: "Please enter your name",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "b",
  //   type: "text",
  //   text: "Please enter your department",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "f",
  //   type: "yes/no",
  //   text: "Are you a Student?",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "c",
  //   type: "number",
  //   text: "Please enter your salary",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "d",
  //   type: "number",
  //   text: "Please enter your bonus",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "e",
  //   type: "number",
  //   text: "Your total income is:",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "l",
  //   type: "file",
  //   text: "Please upload your resume",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   calculationFormula: calculation,
  //   validation: validation,
  //   validationError: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "7",
  //   type: "Number",
  //   text: "",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // {
  //   id: "8",
  //   type: "Number",
  //   text: "",
  //   value: "",
  //   placeholder: "",
  //   defaultValue: "",
  //   editable: true,
  //   required: false,
  //   minLength: "",
  //   maxLength: "",
  //   regex: "",
  // },
  // Add more questions as needed
];